import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { withSessionSsr } from "@/lib/utils/iron-session";
import { getSession } from "@/hooks/getSession";

export const getServerSideProps = withSessionSsr(async ({ req, res }) => {
  const { user, token } = await getSession(req, res);
  return {
    props: { user, token },
  };
});

export default function Home({ user, token }) {
  console.log("State from SSR : ", { token, user });
  const username = user?.username;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Home Page</h1>
        {username && <h3>Hi again {username}</h3>}
      </main>
    </>
  );
}
